name: Solution Project Status Template
description: Template for tracking solution project status
title: "[Solution]: "
labels: ["solution-overview"]
projects: ["NASA-IMPACT/139"]

body:
  - type: markdown
    attributes:
      value: |
        # 📊 Solution Project Status Report

  - type: dropdown
    id: project-status
    attributes:
      label: Status
      options:
        - "✅ Operational"
        - "Planning"
        - "Development"
        - "Maintenance"
    validations:
      required: true

  - type: input
    id: funded-until
    attributes:
      label: Funded Until
      placeholder: "Enter funding end date"
    validations:
      required: true

  - type: input
    id: implementation-lead
    attributes:
      label: 👨‍💼 Implementation Lead
      placeholder: "Name"
    validations:
      required: true

  - type: input
    id: project-scientist
    attributes:
      label: 🔬 Project Scientist
      placeholder: "Name"
    validations:
      required: true

  - type: input
    id: partner-org
    attributes:
      label: 🤝 Partner Organization
      placeholder: "Organization name"
    validations:
      required: true

  - type: dropdown
    id: assessment-cycle
    attributes:
      label: Assessment Cycle
      options:
        - "1 (2016)"
        - "2 (2018)"
        - "3 (2020)"
        - "4 (2022)"
        - "5 (2024)"
    validations:
      required: true

  - type: checkboxes
    id: thematic-areas
    attributes:
      label: 🎯 Thematic Areas
      description: Select all applicable thematic areas for this solution
      options:
        - label: Atmospheric Composition
        - label: Carbon Cycle & Ecosystems
        - label: Disaster Response
        - label: Earth Surface & Interior
        - label: Infrastructure/Other
        - label: Land Cover/Land Use Change
        - label: Ocean & Cryosphere
        - label: Water & Energy Cycle
        - label: Weather & Atmospheric Dynamics
    validations:
      required: true

  - type: input
    id: stakeholder-survey
    attributes:
      label: 📝 Stakeholder Survey
      placeholder: "https://docs.google.com/..."

  - type: input
    id: product-url
    attributes:
      label: 🔗 Primary Product URL
      placeholder: "Enter product URL"
    validations:
      required: true

  - type: textarea
    id: product-description
    attributes:
      label: Product Description
      placeholder: "Brief description of the product and its purpose..."
      value: "Enter a brief description of the product and its purpose..."
    validations:
      required: true

  - type: input
    id: sep-board
    attributes:
      label: 📋 SEP Board
      placeholder: "https://github.com/..."

  - type: dropdown
    id: sep-mandate
    attributes:
      label: SNWG MO Mandate Status
      options:
        - "⏳ Pending Review"
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: key-stakeholders
    attributes:
      label: Key Stakeholders
      value: |
        - 🛰️ SPoRT
        - 👥 Solution Project Implementation Team
        - 🔍 OPERA
    validations:
      required: true

  - type: input
    id: user-assessment-results
    attributes:
      label: 🔮 Results
      placeholder: "Enter assessment results URL"

  - type: input
    id: assessment-folder
    attributes:
      label: 🗃️ Drive Folder
      placeholder: "Enter drive folder URL"

  - type: input
    id: portal-url
    attributes:
      label: 🌐 NASA/ST Portal
      placeholder: "https://earthdata.nasa.gov/..."

  - type: input
    id: training-url
    attributes:
      label: 📚 Training Resources
      placeholder: "https://github.com/..."

  - type: input
    id: toolkit-url
    attributes:
      label: 🛠️ Implementation Tools
      placeholder: "https://github.com/..."

  - type: input
    id: sow-url
    attributes:
      label: 📄 Statement of Work
      placeholder: "https://docs.google.com/..."

  - type: checkboxes
    id: pre-formulation
    attributes:
      label: Pre-Formulation Phase
      options:
        - label: 🎬 HQ Kickoff
        - label: 🤝 Solution Provider Kickoff
        - label: 📝 Project Plan Draft
        - label: 🎯 ATP DG Milestone
        - label: ✍️ ATP DG Memo Completion

  - type: checkboxes
    id: formulation
    attributes:
      label: Formulation Phase
      options:
        - label: 📊 DAAC Selection Product Summary
        - label: 🗣️ Agency Stakeholder Co-design Sessions
        - label: ✅ ESDIS DAAC Selection Process
        - label: 📜 Inter-Project Agreement
        - label: 📄 Interface Control Document
        - label: 📋 Project Plan Finalization
        - label: 🎯 F2I DG Completion
        - label: ✅ Project Plan Baseline

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Phase
      options:
        - label: 🧪 Operational Testing
        - label: 🎯 ORR Completion

  - type: checkboxes
    id: operations
    attributes:
      label: Operations Phase
      options:
        - label: ✅ PVR Completion
        - label: 🚀 Provisional Operations Launch
        - label: 🌟 Validated Operations Launch
        - label: 📦 Project Closeout
        - label: 📢 Closeout Announcement
        - label: 📝 Final Report Preparation
        - label: ✍️ DG Memo Processing
        - label: 🗄️ Documentation Archival

  - type: dropdown
    id: fact-sheet
    attributes:
      label: Fact Sheet
      options:
        - "Not yet developed"
        - "In Development"
        - "Complete"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        *Note: 🔒 Some linked documents may require additional access permissions.*
